### ISSUE TITLE
Consiglio di aggiungere file `LICENSE.txt`

### ISSUE THREAD

**Issue by Fupete** [chialab/titillium_pro#3]
Progetto moooolto bello. Bravissimi.  

Consiglio di aggiungere la licenza [OFL](https://openfontlicense.org/) in file dedicato, [qui es. dall'Inter](https://github.com/rsms/inter/blob/master/LICENSE.txt). Con le righe iniziali di Copyright per l'attribuzione corretta, o il link al file autori. Così GitHub mostrerà la licenza anche nell'interfaccia della repository.

**Comment by deliant88** [comment]
Si aggiorno subito!

**Comment by Fupete** [comment]
Ciao @deliant88, credo nella licenza per correttezza d'uso della OFL dovrebbe rimanere anche Accademia di Belle Arti di Urbino no?, direttamente dentro come secondo rigo oppure in un file `AUTHORS.md` dedicato. (FYI @libremente, questo il progetto di cui ti scrivevo...)
